#!/usr/bin/env sh
source ./vars &&
  aws iam create-role --role-name TerraformAdminRole \
    --assume-role-policy-document "${admin_assume_role_policy}" \
    --description "Terraform AdministratorAccess role to provision infrastructure" &&
  aws iam attach-role-policy --role-name TerraformAdminRole --policy-arn arn:aws:iam::aws:policy/AdministratorAccess
