#!/usr/bin/env sh
if [[ -z ${ADMIN_ACCOUNT_ID} ]]; then
  exit 1
else
  export admin_assume_role_policy="{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::${ADMIN_ACCOUNT_ID}:user/TerraformAdmin\"},\"Action\":\"sts:AssumeRole\"}]}"
  export child_assume_role_policy="{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::${ADMIN_ACCOUNT_ID}:role/TerraformAdminRole\"},\"Action\":\"sts:AssumeRole\"}]}"
fi
